codecov:
  require_ci_to_pass: yes
coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default: fals
      tests:
        target: 100%
        paths: "tests/"
      app:  # declare a new status context "app"
        paths: "!tests/"  # remove all files in "tests/"
    patch: off
    changes: no
parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no
comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: yes
ignore:
  - tests/*
  - docs/*
